"""Database creation

Revision ID: d3b909a65a2a
Revises: 
Create Date: 2024-02-13 19:19:55.439866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b909a65a2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('position_cur', sa.Integer(), nullable=True),
    sa.Column('position_prev', sa.Integer(), nullable=True),
    sa.Column('stars', sa.String(), nullable=True),
    sa.Column('watchers', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('open_issues', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repos')
    # ### end Alembic commands ###
